version: "3"
services:

  redis:
    image: redis
    restart: always
    hostname: redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander
    environment: 
      REDIS_PORT: "6379"
      REDIS_HOST: "redis" 
    ports: 
      - 8081:8081
    links: 
      - redis 

  retwis:
    build: ./retwis
    ports: 
      - 8082:80
    links: 
      - redis       

  jupyter:
    image: ist769/jupyter_pyspark:20210924b 
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes       
    ports:
      - "8888:8888"
    volumes: 
      - ./work:/home/jovyan/work
      - ../../datasets:/home/jovyan/datasets
    depends_on:
      - redis
    links:
      - redis
