version: '3'
services:
  drill:
    image: apache/drill:1.19.0
    container_name: drill
    command: /bin/bash
    tty: true
    ports:
    - "8047:8047"
    - "31010:31010"
    ulimits:
      memlock: -1
      nproc: 32768
      nofile: 100000

  #jupyter - TODO CLIENT INSTALLS AND Spark CONFIGS#
  jupyter:
    image: ist769/jupyter_pyspark:20210924b 
    container_name: jupyter
    environment:
      - GRANT_SUDO=yes
      - JUPYTER_ENABLE_LAB=yes       
    ports:
      - "8888:8888"
    volumes: 
      - ./work:/home/jovyan/work
      - ../../../datasets:/home/jovyan/datasets
    env_file:
      - ./hadoop-hive.env
    
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    volumes:
      - hdfs-namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=hive
      - hadoop-config:/etc/hadoop:rw
    env_file:
      - ./hadoop-hive.env
    ports:
      - "50070:50070"

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - hdfs-datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop-hive.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    ports:
      - "50075:50075"

  hive-server:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-server
    volumes:
      - ./employee:/employee
    env_file:
      - ./hadoop-hive.env
    environment:
      HIVE_CORE_CONF_javax_jdo_option_ConnectionURL: "jdbc:postgresql://hive-metastore/metastore"
      SERVICE_PRECONDITION: "hive-metastore:9083"
    depends_on:
      - hive-metastore
    ports:
      - "10000:10000"

  hive-metastore:
    image: bde2020/hive:2.3.2-postgresql-metastore
    container_name: hive-metastore
    env_file:
      - ./hadoop-hive.env
    command: /opt/hive/bin/hive --service metastore
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 hive-metastore-postgresql:5432"
    depends_on:
      - hive-metastore-postgresql
    ports:
      - "9083:9083"

  hive-metastore-postgresql:
    image: bde2020/hive-metastore-postgresql:2.3.0
    container_name: hive-metastore-postgresql
    volumes:
      - metastore-postgresql:/var/lib/postgresql/data
    depends_on:
      - datanode


volumes:
  metastore-postgresql:
  hdfs-datanode:
  hdfs-namenode:


networks:
  default:
    name: foo